name: 8Puzzle CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-app:
    runs-on: ubuntu-latest # 22.04 bionic
    # env:
    # API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update -q && sudo apt-get install -y g++-11

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Build Code
        run: g++ -std=c++11 -g -w *.cpp -o puzzle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cplusplus-artifact
          path: puzzle

  second-step:
    runs-on: ubuntu-latest # 22.04 bionic
    needs: Run-app
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: cplusplus-artifact
          path: .

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Set permissions
        run: chmod +x puzzle

      - name: Run the puzzle program
        run: |
          expect -c '
            spawn ./puzzle
            expect "Enter a valid 8-Puzzle one digit at a time similar to the above format while entering 0 for the desired blank."
            send "1 2 3 4 5 6 7 8 0\r"
            expect "This 8-puzzle has 0 inversions and is valid."
            expect "Enter 0 for Best-first and 1 for A*:"
            send "1\r"
            expect "Choose your desired heuristic:"
            expect "0) Out-of-place Tile"
            expect "1) Manhattan"
            expect "2) Linear Conflict"
            send "0\r"
            '
