name: 8Puzzle CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-app:
    runs-on: ubuntu-latest # 22.04 bionic
    # env:
    # API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update -q && sudo apt-get install -y g++-11

      - name: Build Code
        run: g++ -std=c++11 -g -w *.cpp -o puzzle

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cplusplus-artifact
          path: puzzle

  second-step:
    runs-on: ubuntu-latest # 22.04 bionic
    needs: Run-app
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: cplusplus-artifact
          path: .

      - name: Set permissions
        run: chmod +x puzzle

      - run: ./puzzle

      - run: 1 2 3 4 5 6 7 8 0

      - run: 1

      - run: 0
